# Generated by Django 4.1.13 on 2024-05-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('location', models.CharField(max_length=255, null=True)),
                ('contact', models.CharField(max_length=100, null=True)),
                ('establish_date', models.DateField(null=True)),
                ('state', models.CharField(help_text='Size of the company', max_length=100, null=True)),
                ('field_of_work', models.CharField(max_length=255, null=True)),
                ('added_info', models.TextField(null=True)),
            ],
        ),
    ]
