# Generated by Django 4.1.13 on 2024-05-15 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0002_remove_jobpost_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobApplication',
        ),
    ]
