# Generated by Django 4.1.13 on 2024-05-14 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options_customuser_email_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveIndex(
            model_name='customuser',
            name='email_idx',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='bio',
        ),
    ]
