# Generated by Django 4.1.13 on 2024-05-17 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_phone_number_customuser_user_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
